import type { MarketConfig } from "@/lib/validation/market";

export const RISK_DISCLOSURE_VERSION = "2026-05-13";

export const DEFAULT_MARKETS: MarketConfig[] = [
  {
    id: "seed-test-abc",
    symbol: "test:ABC",
    displayName: "Test ABC Derived Perpetual",
    baseAsset: "ABC",
    quoteAsset: "USDC",
    hyperliquidAssetId: 110000,
    hyperliquidCoin: "test:ABC",
    hyperliquidDex: "test",
    isHip3: true,
    oracleDescription:
      "Hyperliquid docs example HIP-3 testnet market. Verify from testnet meta before production use.",
    maxLeverage: 3,
    minOrderSize: 0.001,
    tickSize: 0.01,
    szDecimals: 3,
    enabled: true,
    testnetOnly: true
  },
  {
    id: "seed-aapl",
    symbol: "AAPL-PERP",
    displayName: "Apple Derived Perpetual",
    baseAsset: "AAPL",
    quoteAsset: "USDC",
    hyperliquidAssetId: 750009,
    hyperliquidCoin: "xyz:AAPL",
    hyperliquidDex: "xyz",
    isHip3: true,
    oracleDescription: "Verified on Hyperliquid testnet xyz dex. Coin xyz:AAPL, asset ID 750009.",
    maxLeverage: 20,
    minOrderSize: 0.001,
    tickSize: 0.01,
    szDecimals: 3,
    enabled: true,
    testnetOnly: true
  },
  {
    id: "seed-tsla",
    symbol: "TSLA-PERP",
    displayName: "Tesla Derived Perpetual",
    baseAsset: "TSLA",
    quoteAsset: "USDC",
    hyperliquidAssetId: 750001,
    hyperliquidCoin: "xyz:TSLA",
    hyperliquidDex: "xyz",
    isHip3: true,
    oracleDescription: "Verified on Hyperliquid testnet xyz dex. Coin xyz:TSLA, asset ID 750001.",
    maxLeverage: 10,
    minOrderSize: 0.001,
    tickSize: 0.01,
    szDecimals: 3,
    enabled: true,
    testnetOnly: true
  },
  {
    id: "seed-nvda",
    symbol: "NVDA-PERP",
    displayName: "NVIDIA Derived Perpetual",
    baseAsset: "NVDA",
    quoteAsset: "USDC",
    hyperliquidAssetId: 750002,
    hyperliquidCoin: "xyz:NVDA",
    hyperliquidDex: "xyz",
    isHip3: true,
    oracleDescription: "Verified on Hyperliquid testnet xyz dex. Coin xyz:NVDA, asset ID 750002.",
    maxLeverage: 20,
    minOrderSize: 0.001,
    tickSize: 0.01,
    szDecimals: 3,
    enabled: true,
    testnetOnly: true
  },
  {
    id: "seed-meta",
    symbol: "META-PERP",
    displayName: "Meta Derived Perpetual",
    baseAsset: "META",
    quoteAsset: "USDC",
    hyperliquidAssetId: 750008,
    hyperliquidCoin: "xyz:META",
    hyperliquidDex: "xyz",
    isHip3: true,
    oracleDescription: "Verified on Hyperliquid testnet xyz dex. Coin xyz:META, asset ID 750008.",
    maxLeverage: 10,
    minOrderSize: 0.001,
    tickSize: 0.01,
    szDecimals: 3,
    enabled: true,
    testnetOnly: true
  },
  {
    id: "seed-amzn",
    symbol: "AMZN-PERP",
    displayName: "Amazon Derived Perpetual",
    baseAsset: "AMZN",
    quoteAsset: "USDC",
    hyperliquidAssetId: 750013,
    hyperliquidCoin: "xyz:AMZN",
    hyperliquidDex: "xyz",
    isHip3: true,
    oracleDescription: "Verified on Hyperliquid testnet xyz dex. Coin xyz:AMZN, asset ID 750013.",
    maxLeverage: 10,
    minOrderSize: 0.001,
    tickSize: 0.01,
    szDecimals: 3,
    enabled: true,
    testnetOnly: true
  },
  {
    id: "seed-msft",
    symbol: "MSFT-PERP",
    displayName: "Microsoft Derived Perpetual",
    baseAsset: "MSFT",
    quoteAsset: "USDC",
    hyperliquidAssetId: 750010,
    hyperliquidCoin: "xyz:MSFT",
    hyperliquidDex: "xyz",
    isHip3: true,
    oracleDescription: "Verified on Hyperliquid testnet xyz dex. Coin xyz:MSFT, asset ID 750010.",
    maxLeverage: 10,
    minOrderSize: 0.001,
    tickSize: 0.01,
    szDecimals: 3,
    enabled: true,
    testnetOnly: true
  },
  {
    id: "seed-googl",
    symbol: "GOOGL-PERP",
    displayName: "Alphabet Derived Perpetual",
    baseAsset: "GOOGL",
    quoteAsset: "USDC",
    hyperliquidAssetId: 750012,
    hyperliquidCoin: "xyz:GOOGL",
    hyperliquidDex: "xyz",
    isHip3: true,
    oracleDescription: "Verified on Hyperliquid testnet xyz dex. Coin xyz:GOOGL, asset ID 750012.",
    maxLeverage: 10,
    minOrderSize: 0.001,
    tickSize: 0.01,
    szDecimals: 3,
    enabled: true,
    testnetOnly: true
  },
  {
    id: "seed-spy",
    symbol: "SPY-PERP",
    displayName: "SPY Derived Perpetual",
    baseAsset: "SPY",
    quoteAsset: "USDC",
    hyperliquidAssetId: null,
    isHip3: true,
    oracleDescription: "Pending verified HIP-3 oracle and meta asset ID.",
    maxLeverage: 5,
    minOrderSize: 0.001,
    tickSize: 0.01,
    szDecimals: 3,
    enabled: false,
    testnetOnly: true
  }
];
